### ISSUE TITLE
Meta.yml wrong.

### ISSUE THREAD

**Issue by EvanCarroll** [ingydotnet/xxx-pm#3]
# Example

https://metacpan.org/source/INGY/XXX-0.18/META.yml
# Links

The homepage should not be `/xxx-pm/tree`.. That url is not valid.

``` resources:
  homepage: http://github.com/ingydotnet/xxx-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/xxx-pm.git
```
# Bugtracker

maybe consider adding

bugtracker: https://github.com/ingydotnet/xxx-pm/issues/

**Comment by perlpunk** [comment]
This seems to be fixed, closing
